- name: Ansible fact - ansible_date_time.iso8601
  lineinfile:
    path: "{{ project_path }}/stats.yml"
    line: "build_date: {{ ansible_date_time.iso8601 }}"
  tags: redeploy

- name: Update stats.yml
  lineinfile:
    path: "{{ project_path }}/stats.yml"
    line: "hop1_ip: {{ deployment.outputs.hop1_public_ip.value }}"

# Use correct username based on provider
# Might a better way of doing this
- name: Add host
  add_host:
    name: hop1
    ansible_host: "{{ deployment.outputs.hop1_public_ip.value }}"
    groups: "{{ provider1 }}_hop1"
    ansible_ssh_private_key_file: "{{ project_path }}/id_ssh_rsa"
    ansible_user: debian
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ansible_python_interpreter: /usr/bin/python3
  when: provider1 == "azure"
  tags: redeploy

- name: Add host
  add_host:
    name: hop1
    ansible_host: "{{ deployment.outputs.hop1_public_ip.value }}"
    groups: "{{ provider1 }}_hop1"
    ansible_ssh_private_key_file: "{{ project_path }}/id_ssh_rsa"
    ansible_user: admin
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ansible_python_interpreter: /usr/bin/python3
  when: ( provider1 == "aws" or provider1 == "gcp" )
  tags: redeploy

- name: Add host
  add_host:
    name: hop1
    ansible_host: "{{ deployment.outputs.hop1_public_ip.value }}"
    groups: "{{ provider1 }}_hop1"
    ansible_ssh_private_key_file: "{{ project_path }}/id_ssh_rsa"
    ansible_user: root
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ansible_python_interpreter: /usr/bin/python3
  when: ( provider1 == "linode" or provider1 == "exoscale" or provider1 == "vultr" )

- name: Sleep for 3
  wait_for:
    timeout: 3
  tags: redeploy
