---
- name: Create stats file
  template:
    src: stats.yml
    dest: "{{ project_path }}/stats.yml"

- name: Update stats.yml
  local_action:
    module: lineinfile
    path: "{{ project_path }}/stats.yml"
    line: 'username: "{{ rand_username }}"'

- name: Update stats.yml
  local_action:
    module: lineinfile
    path: "{{ project_path }}/stats.yml"
    line: 'project_id: "{{ project_id }}"'

- name: Update stats with hop1 port
  lineinfile:
    path: "{{ project_path }}/stats.yml"
    line: "hop1_port: {{ hop1_port }}"

- name: Update stats with hop2 port
  lineinfile:
    path: "{{ project_path }}/stats.yml"
    line: "hop2_port: {{ hop2_port }}"

- name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
  community.crypto.openssh_keypair:
    path: "/{{ project_path }}/id_ssh_rsa"

# Update fact prior to template
- set_fact:
    hop_name: "{{ hop1_name }}"

- name: Copy main.tf 1
  template:
    src: "{{ provider1 }}.tf.tmpl"
    dest: "{{ project_path }}/hop1_{{ provider1 }}.tf"

# Update fact prior to template
- set_fact:
    hop_name: "{{ hop2_name }}"

- name: Copy main.tf 2
  template:
    src: "{{ provider2 }}.tf.tmpl"
    dest: "{{ project_path }}/hop2_{{ provider2 }}.tf"

- name: Move vars file 1
  template:
    src: "{{ provider1 }}/vars.tf.tmpl"
    dest: "{{ project_path}}/modules/hop1_{{ provider1 }}/vars.tf"

- name: Set name
  replace:
    path: "{{ project_path}}/modules/hop1_{{ provider1 }}/vars.tf"
    regexp: "namenamenamename"
    replace: "{{ project_path }}1"

- name: Set wireguard port
  replace:
    path: "{{ project_path}}/modules/hop1_{{ provider1 }}/vars.tf"
    regexp: "wireguardport"
    replace: "{{ hop1_port }}"

- name: Move vars file 2
  template:
    src: "{{ provider2 }}/vars.tf.tmpl"
    dest: "{{ project_path }}/modules/hop2_{{ provider2 }}/vars.tf"

- name: Set name
  replace:
    path: "{{ project_path}}/modules/hop2_{{ provider2 }}/vars.tf"
    regexp: "namenamenamename"
    replace: "{{ project_path }}"

- name: Set wireguard port
  replace:
    path: "{{ project_path}}/modules/hop2_{{ provider2 }}/vars.tf"
    regexp: "wireguardport"
    replace: "{{ hop2_port }}"

- name: Deploy resources 
  terraform:
    project_path: "{{ project_path }}"
    force_init: true
    state: present
  register: deployment

- name: Host 1
  include_tasks: host1.yml

- name: Host 2
  include_tasks: host2.yml
