---
- name: Set Client Conf File Tunnel 2
  become: true
  template:
    src: templates/wg2-client.conf
    dest: /etc/wireguard/wg2-client.conf
  with_items: "{{ hop0_host }}"
  tags: redeploy

- name: Set Server Conf File Tunnel 3
  become: true
  template:
    src: templates/wg3.conf
    dest: /etc/wireguard/wg3.conf
  with_items: "{{ hop0_host }}"
  tags: redeploy

- name: Setup VPN Namespace
  become: true
  shell: |
    ip netns add wireguard
    ip link add wg2-client type wireguard
    ip link set netns wireguard dev wg2-client
    ip -n wireguard addr add 10.2.1.2/24 dev wg2-client
    ip link add wg3 type wireguard
    ip link set netns wireguard dev wg3
    ip -n wireguard addr add 10.3.1.1/24 dev wg3
    ip netns exec wireguard wg setconf wg2-client /etc/wireguard/wg2-client.conf
    ip netns exec wireguard wg setconf wg3 /etc/wireguard/wg3.conf
    ip -n wireguard link set wg2-client up
    ip -n wireguard link set wg3 up
    ip -n wireguard route add default dev wg2-client
    ip netns exec wireguard iptables -F
    ip netns exec wireguard iptables -t nat -I POSTROUTING -o wg2-client -j MASQUERADE
  tags: redeploy
