---
- name: Set Client Conf File Tunnel 1
  become: true
  template:
    src: templates/wg1-client.conf
    dest: /etc/wireguard/wg1-client.conf
  with_items: "{{ hop1_host }}"
  tags: redeploy

- name: Set Server Conf File Tunnel 2
  become: true
  template:
    src: templates/wg2.conf
    dest: /etc/wireguard/wg2.conf
  with_items: "{{ hop1_host }}"
  tags: redeploy

