---
- name: Push stream.conf
  become: true
  template:
    src: templates/stream.conf
    dest: /root/stream.conf

- name: Create nginx container
  docker_container:
    name: nginx
    image: nginx
    volumes:
      - /root/stream.conf:/etc/nginx/nginx.conf
    published_ports: "{{ nginx_listen_port }}:{{ nginx_listen_port }}"
