---
- name: Install Wireguard
  become: true
  apt:
    name:
      - wireguard

- name: Create wireguard container
  become: true
  docker_container:
    name: wireguard
    image: lscr.io/linuxserver/wireguard
    volumes:
      - /root/wg_configs:/config
      - /lib/modules:/lib/modules
    ports: "{{ wg_port }}:51820/udp"
    capabilities:
      - net_admin
      - sys_module
    env:
      PUID: "1000"
      PGID: "1000"
      PEERS: "5"
      TZ: "Etc/UTC"
      PERSISTENTKEEPALIVE_PEERS: "all"
      SERVERURL: "{{ hop1_ip }}"
      SERVERPORT: "{{ wg_port }}"
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1

- name: Retrieve wireguard configs
  synchronize:
    recursive: true
    mode: pull
    src: /root/wg_configs
    dest: "/tmp/{{ project_id}}/"



