---
- name: Update DNS
  become: true
  shell: echo "nameserver 1.1.1.1" >> /etc/resolv.conf

- name: Install Unbound and Wireguard
  become: true
  apt:
    name:
      - unbound

- name: Copy Unbound Config File
  become: true
  template:
    src: templates/unbound.conf

- name: Stop Systemd-Resolved
  become: true
  systemd:
    name: systemd-resolved
    state: stopped

- name: Disable Systemd-Resolved
  become: true
  systemd:
    name: systemd-resolved
    enabled: no
    masked: yes

- name: Enable Unbound
  become: true
  systemd:
    name: unbound
    enabled: yes
    masked: no

- name: Grab DNS file
  become: true
  shell: curl -o /var/lib/unbound/root.hints https://www.internic.net/domain/named.cache

- name: Start Unbound
  become: true
  systemd:
    name: unbound
    state: restarted

- name: Enable Unbound-resolvconf
  become: true
  systemd:
    name: unbound-resolvconf
    enabled: yes
    masked: no

- name: Start Unbound-Resolvconf
  become: true
  systemd:
    name: unbound-resolvconf
    state: restarted

- name: Chown unbound directory
  become: true
  file:
    path: /var/lib/unbound
    state: directory
    recurse: yes
    owner: unbound
    group: unbound
