---
- name: Install Wireguard
  become: true
  apt:
    name:
      - wireguard

- name: Create wireguard container
  docker_container:
    name: wireguard
    image: lscr.io/linuxserver/wireguard
    volumes:
      - /root/wg_config:/config
      - /lib/modules:/lib/modules
    ports: "{{ wg_port }}:51820/udp"
    capabilities:
      - net_admin
      - sys_module
    env:
      PUID: "1000"
      PGID: "1000"
      PEERS: "1"
      TZ: "Etc/UTC"
      PERSISTENTKEEPALIVE_PEERS: "30"
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1



