---
- name: Baseline nodes
  include_tasks: baseline.yml
  tags: redeploy

- name: Enable IP Forwarding
  become: yes
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

# Harden SSH
- name: Disable empty password login
  become: yes
  lineinfile: dest={{ sshd_config }} regexp="^#?PermitEmptyPasswords" line="PermitEmptyPasswords no"

- name: Disable password login
  become: yes
  lineinfile: dest={{ sshd_config }} regexp="^(#\s*)?PasswordAuthentication " line="PasswordAuthentication no"
  notify: "restart ssh"

# - name: Setup Hop 1
#   include_tasks: hop1.yml
#   when: inventory_hostname == 'hop1'
#
# - name: Setup Hop 2
#   include_tasks: hop2.yml
#   when: inventory_hostname == 'hop2'
#
#
