---
- hosts: localhost
  tasks:
    - name: Deploy role
      include_role:
        name: ./roles/build

  vars:
    hop1_name: "hop1_{{ provider1 }}"
    hop2_name: "hop2_{{ provider2 }}"
    project_path: "{{ project_path }}"
    project_id: "{{ project_id }}"
    hop1_resource_name: "{{ hop1_resource_name }}"
    hop2_resource_name: "{{ hop2_resource_name }}"

- hosts: ephemeral
  tasks:
    - name: Ping all hosts
      ansible.builtin.ping:

    - name: Provision role
      include_role:
        name: ./roles/provision
      vars:
        hop1_ip: "{{ hostvars['hop1'].ansible_host }}"
        hop2_ip: "{{ hostvars['hop2'].ansible_host }}"
        wg_port: "{{ wg_port }}"
